### ISSUE TITLE
Add bios to project

### ISSUE THREAD

**Issue by hubyeti** [journyman65/github-for-developers-7#3]
We should all create great bios in this project. Make sure your bio includes:

```
     - [ ] Your name
     - [ ] Where you are from
     - [ ] A favorite food
     - [ ] A hobby
```

**Comment by journyman65** [comment]
When creating your bio, please make sure all requested information is listed, your bio should read as follows, My name is Joseph Duran, I'm from Billings Montana, my favorite food is fried chicken, my hobbies include hunting deer, antalope, and elk, or fishing trout Bass and ling. Thank you
